export { SURFACE_META } from './registry'
export type { SurfaceMeta, SurfaceDataKind } from './registry'
export { SurfacePlaceholder } from './SurfacePlaceholder'
export { TerminalSurface } from './TerminalSurface'
export { EditorSurface } from './EditorSurface'
export { BrowserSurface } from './BrowserSurface'
export { ClaudeSurface } from './ClaudeSurface'
export { ContainerFileBrowser, ContainerFileBrowserView } from './ContainerFileBrowser'
export type { ContainerFileBrowserProps, FileBrowserMode } from './ContainerFileBrowser'
export { joinContainerPath, parentContainerPath } from './containerPath'
